### ISSUE TITLE
Замечания по lw6

### ISSUE THREAD

**Issue by ivklgn** [ITNoobCC/Web#6]
при структурировании проекта нужно определится, либо вы делаете в отдельных папках отдельное использование npm-automation-env, либо вы делаете конфиг для мультипроектов.

**Comment by ivklgn** [comment]
**Blog**

1. navbar_container - скорее всего блок
2. у всех элементов должны быть классы
3. navbar_container_menu_link неверно, маска: `block-name_element-name--modificator-name` - поправить везде
4. не хватает БЭМ-блока:
```html
<h4>Featured Posts:</h4>
<p><a href="">PREVIOUS POST ABOUT SOMETHING</a></p>
<p><a href="">PREVIOUS POST ABOUT SOMETHING</a></p>
```

**Comment by ivklgn** [comment]
**Chat**

1. UI: сделайте область для сообщений и фиксированный блок для отправки
2. https://developer.mozilla.org/ru/docs/Mozilla/Mobile/Viewport_meta_tag
3. в css нарушено кол-во отступов
4. используйте классы

```css
button {
    margin: 1% 40%;
    font-size: 200%;
    border-radius: 10px;
}
label {
    margin: 0 0 0 -40%;
    color: white;
    font-size: 200%;
    size: 200%;
}
```

5. код не по БЭМ
